In [2]:
#importing necessary libraries.
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/FinalDataset.csv")
data.head()

   Unnamed: 0  Gender      Stream    Subject  Marks Course Specialization
0           0   Male      Science   Physiscs   78.0  btech          Civil
1           1  Female        Arts      Maths   68.0  mtech          Maths
2           2   Male     Commerce    history   32.0     ba        history
3           3  Female     Science  economics   54.0   bcom           hons
4           4   Male   Humanities  chemistry   31.0    bsc        biology

In [3]:
descriptions =data['Gender'] +' '+ data['Subject'] + ' ' + data['Stream'] +' '+ data['Marks'].apply(str)
#Printing the first description
descriptions[0]

'Male  Physiscs Science 78.0'

In [9]:
# import TfidfVector from sklearn.
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
def create_similarity_matrix(new_description, overall_descriptions):
#Append the new description to the overall set.
      overall_descriptions.append(new_description)
        # Define a tfidf vectorizer and remove all stopwords.
      tfidf = TfidfVectorizer(stop_words="english")
        #Convert tfidf matrix by fitting and transforming the data.
      tfidf_matrix = tfidf.fit_transform(overall_descriptions)
        # output the shape of the matrix.
      tfidf_matrix.shape
        # calculating the cosine similarity matrix.
      cosine_sim = linear_kernel(tfidf_matrix,tfidf_matrix)
      return cosine_sim

In [11]:
def get_recommendations(new_description,overall_descriptions):
# create the similarity matrix
  cosine_sim = create_similarity_matrix(new_description,overall_descriptions)
# Get pairwise similarity scores of all the students with new student.
  sim_scores = list(enumerate(cosine_sim[-1]))
# Sort the descriptions based on similarity score.
  sim_scores = sorted(sim_scores,key =lambda x:x[1],reverse= True )
# Get the scores of top 10 descriptions.
  sim_scores = sim_scores[1:10]
# Get the student indices.
  indices = [i[0]for i in sim_scores]
  return data.iloc[indices]

In [12]:
new_description = pd.Series('male physics science 78')
get_recommendations(new_description,descriptions)

   Unnamed: 0  Gender      Stream    Subject  Marks Course Specialization
0           0   Male      Science   Physiscs   78.0  btech          Civil
5           5  Female     Science   Physiscs   20.2  btech          Civil
8           8   Male      Science  economics   98.0   bcom           hons
3           3  Female     Science  economics   54.0   bcom           hons
6           6   Male         Arts      Maths    9.4  mtech          Maths
2           2   Male     Commerce    history   32.0     ba        history
4           4   Male   Humanities  chemistry   31.0    bsc        biology
1           1  Female        Arts      Maths   68.0  mtech          Maths
7           7  Female    Commerce    history   76.0     ba        history